flags: {}
extra-package-dbs: []
packages:
- .
extra-deps:
- HDBC-postgresql-2.3.2.5
- HDBC-sqlite3-2.3.3.1
- cabal-macosx-0.2.4.1
- reactive-banana-wx-1.1.1.0
- wx-0.92.3.0
- wxc-0.92.3.0
- wxcore-0.92.3.0
- wxdirect-0.92.3.0
explicit-setup-deps:
  ! '*': true
resolver: lts-9.13
